# pytorch_study

In [1]:
import torch
import numpy as np

In [2]:
list1 = ([1,2], [3,4])

In [3]:
example_tensor = torch.tensor(list1)

In [4]:
example_tensor

tensor([[1, 2],
        [3, 4]])

In [5]:
type(example_tensor)

torch.Tensor

In [7]:
list2 = [1,2,3,4,5]

In [8]:
type(list2)

list

In [10]:
example_tensor = torch.tensor(list2)

In [11]:
example_tensor # 토치에서는 데이터를 던져주면 텐서로 만들어준다.

tensor([1, 2, 3, 4, 5])

In [12]:
type(example_tensor)

torch.Tensor

In [13]:
np_tensor = torch.tensor(np.array([1,2,3,4,5,6]))

In [14]:
np_tensor

tensor([1, 2, 3, 4, 5, 6], dtype=torch.int32)

In [15]:
type(np_tensor) # 자료형만 던져주면 텐서로 만들어준다. 

torch.Tensor

In [16]:
example_tensor = torch.tensor(1)
example_tensor

tensor(1)

In [18]:
# 비어있는 텐서 만들기 
empty_tensor = torch.tensor([])
empty_tensor

tensor([])

In [20]:
tensor_float = torch.tensor([3,4,5], dtype = torch.float32)
tensor_float

tensor([3., 4., 5.])