In [1]:
# 별칭으로 tf로 하는 것이 일반적

import tensorflow as tf
print(tf.__version__)

2.5.0


In [5]:
# 일반적으로 우리가 직접 tensor를 생성하는 경우는 없다
# Tensorflow가 tf.io나 ft.data라는 모듈을 기본적으로 가지고 있어서,
# 데이터로 가지고 와서 자동으로 tensor로 전환(변환)을 해줌
# 변환된 텐서를 나중에 neural network(신경망)에서 사용합니다.

# tensor를 이해하기 위헤 직접 만들어본다
# tensorflow 에서 사용하는 상수 (constant)를 생성 

# scalar 를 생성 (rank가 0인 텐서), 스칼라는 어떠한 차원을 가지고 있는 단순한 숫자
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [7]:
# ndim : 해당 텐서의 차원 수를 알려준다.
# ndim : number of dimensions의 약자 
scalar.ndim

0

In [8]:
# 벡터를 생성 
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [9]:
vector.ndim

1

In [11]:
# 행렬 (matrix) 생성 (차원이 1보다 큰것)
matrix = tf.constant([
    [10,10],
    [7,7]
])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 10],
       [ 7,  7]])>

In [12]:
matrix.ndim

2

In [13]:
# Tensorflow는 기본적으로 int32나 float32 자료형으로 tensor를 생성한다.
# 이 뜻은 32-bit precision이다. 숫자가 높으면 높을 수록 정밀도 precision도 높아지고 컴퓨터가 사용할 메모리도 커진다.matrix
# 

In [14]:
# 새로운 행렬을 생성하고 데이터형을 지정
another_matrix = tf.constant([
    [10., 7.],
    [3., 2.],
    [8., 9.],
])
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float32)>

In [15]:
another_matrix = tf.constant([
    [10., 7.],
    [3., 2.],
    [8., 9.],
], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [16]:
another_matrix.ndim

2

In [22]:
# tensor를 생성 (2차원보다 많은것)
tensor = tf.constant([
    [
        [1,2,3],
        [4,5,6],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12],
        [10,11,12]

    ]
], dtype=tf.float64)
tensor

<tf.Tensor: shape=(2, 3, 3), dtype=float64, numpy=
array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 4.,  5.,  6.]],

       [[ 7.,  8.,  9.],
        [10., 11., 12.],
        [10., 11., 12.]]])>

In [20]:
tensor.ndim

3

In [23]:
# rank = dimension
# scalar, vector, maxtrix, tensor로 굳이 앞에서 정의를 했지만 
# 이론적으로는 모두 tensor이다.
# 각각의 rank가 0, 1, 2, 3인 텐서로 이야기 할 수 있다.
# tensor는 임의, 즉 제한이 없는 차원을 가질 수 있다.

In [24]:
# 이미지들을 처리한다고 할때, (224, 224, 3, 32)라고 표현을 할 때 
# 224, 224는 픽셀로 표현했을 때 높이와 너비를 의미하고,
# 3은 이미지의 채널수 (red, green, blue)
# 32는 배치 사이즈 (1번 실행시 신경망이 1번에 처리할 수 있는 이미지의 갯수)

In [25]:
# 위에서 선언한 모든 constant는 모두 tensor에 속하지만, 위에서와 각자의 부른 이름 존재
# scalar : 단일한 숫자 : 0차원 tensor
# vector : 방향이 있는 숫자 : 1차원 tensor 
# matrix : 숫자로 이루어진 2차원 배열 : 2차원 tensorW
# tensor : 숫자로 이루어진 n차원 배열

![스칼라 벡터 텐서 구분하기](00-scalar-vector-matrix-tensor.png)

In [29]:
# 변수 생성
# tf.Variable()

In [30]:
# tf.Variable와 tf.contant의 차이점
# ==> tf.constant로 생성한 텐서는 immutable(변경 불가)
# ==> tf.Variable로 생성한 텐서는 mutable (변경 가능)

In [32]:
changeable_tensor = tf.Variable([10,7])

In [33]:
unchangeable_tensor = tf.constant([10,7])

In [34]:
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [40]:
changeable_tensor[0] = 7

TypeError: 'ResourceVariable' object does not support item assignment

In [41]:
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [42]:
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [43]:
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [44]:
unchangeable_tensor(0).assign(7)

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object is not callable

In [ ]:
# tf.constant 및 tf.Variable 중에 어떤 것을 사용해야 할까요?
# 상황에 따라 다르다! tensorflow가 우리를 위해서 tensor를 직접 생성하는데,
# 이 때 (데이터를 불러올 때나 데이터를 모델링) 알아서 constant 및 Variable를 선택해서 생성합니다.